from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "raw"
PROCESSED = ROOT / "processed"
PROCESSED.mkdir(parents=True, exist_ok=True)

T100_COLUMNS = ['year',
 'month',
 'origin',
 'origin_numeric_code',
 'origin_wac',
 'origin_city_name',
 'destination',
 'destination_numeric_code',
 'destination_wac',
 'destination_city_name',
 'carrier_code',
 'carrier_entity_code',
 'carrier_group_code',
 'distance_miles',
 'service_class',
 'aircraft_group',
 'aircraft_type',
 'aircraft_configuration',
 'departures_performed',
 'departures_scheduled',
 'payload_pounds',
 'seats',
 'passengers',
 'freight_pounds',
 'mail_pounds',
 'ramp_to_ramp_minutes',
 'airborne_minutes',
 'carrier_wac']

INT_FIELDS = {'airborne_minutes',
 'aircraft_configuration',
 'aircraft_group',
 'aircraft_type',
 'carrier_group_code',
 'carrier_wac',
 'departures_performed',
 'departures_scheduled',
 'destination_numeric_code',
 'destination_wac',
 'distance_miles',
 'freight_pounds',
 'mail_pounds',
 'month',
 'origin_numeric_code',
 'origin_wac',
 'passengers',
 'payload_pounds',
 'ramp_to_ramp_minutes',
 'seats',
 'year'}

FINANCIAL_METRICS = {'revenue': {'label': 'Revenue',
             'namespace': 'us-gaap',
             'tags': ['RevenueFromContractWithCustomerExcludingAssessedTax',
                      'Revenues',
                      'SalesRevenueServicesNet'],
             'unit': 'USD',
             'domain': 'Financial Performance'},
 'passenger_revenue': {'label': 'Passenger Revenue',
                       'namespace': 'us-gaap',
                       'tags': ['PassengerRevenue'],
                       'unit': 'USD',
                       'domain': 'Revenue Mix'},
 'passenger_revenue_mainline': {'label': 'Passenger Revenue - Mainline',
                                'namespace': 'us-gaap',
                                'tags': ['PassengerRevenueMainline'],
                                'unit': 'USD',
                                'domain': 'Revenue Mix'},
 'passenger_revenue_regional': {'label': 'Passenger Revenue - Regional',
                                'namespace': 'us-gaap',
                                'tags': ['PassengerRevenueRegional'],
                                'unit': 'USD',
                                'domain': 'Revenue Mix'},
 'cargo_revenue': {'label': 'Cargo & Freight Revenue',
                   'namespace': 'us-gaap',
                   'tags': ['CargoAndFreightRevenue'],
                   'unit': 'USD',
                   'domain': 'Revenue Mix'},
 'operating_income': {'label': 'Operating Income',
                      'namespace': 'us-gaap',
                      'tags': ['OperatingIncomeLoss'],
                      'unit': 'USD',
                      'domain': 'Profitability'},
 'net_income': {'label': 'Net Income',
                'namespace': 'us-gaap',
                'tags': ['NetIncomeLoss'],
                'unit': 'USD',
                'domain': 'Profitability'},
 'operating_cash_flow': {'label': 'Operating Cash Flow',
                         'namespace': 'us-gaap',
                         'tags': ['NetCashProvidedByUsedInOperatingActivities'],
                         'unit': 'USD',
                         'domain': 'Cash Flow'},
 'cash': {'label': 'Cash & Cash Equivalents',
          'namespace': 'us-gaap',
          'tags': ['CashAndCashEquivalentsAtCarryingValue'],
          'unit': 'USD',
          'domain': 'Liquidity'},
 'assets': {'label': 'Total Assets',
            'namespace': 'us-gaap',
            'tags': ['Assets'],
            'unit': 'USD',
            'domain': 'Balance Sheet'},
 'liabilities': {'label': 'Total Liabilities',
                 'namespace': 'us-gaap',
                 'tags': ['Liabilities'],
                 'unit': 'USD',
                 'domain': 'Balance Sheet'},
 'long_term_debt': {'label': 'Long-Term Debt',
                    'namespace': 'us-gaap',
                    'tags': ['LongTermDebt', 'LongTermDebtNoncurrent'],
                    'unit': 'USD',
                    'domain': 'Capital Structure'},
 'debt_total': {'label': 'Total Debt (Long + Short Term)',
                'namespace': 'us-gaap',
                'tags': ['DebtLongtermAndShorttermCombinedAmount'],
                'unit': 'USD',
                'domain': 'Capital Structure'},
 'fuel_costs': {'label': 'Fuel Costs',
                'namespace': 'us-gaap',
                'tags': ['FuelCosts'],
                'unit': 'USD',
                'domain': 'Operating Costs'},
 'labor_costs': {'label': 'Labor & Related Expense',
                 'namespace': 'us-gaap',
                 'tags': ['LaborAndRelatedExpense'],
                 'unit': 'USD',
                 'domain': 'Operating Costs'},
 'maintenance_costs': {'label': 'Aircraft Maintenance Materials & Repairs',
                       'namespace': 'us-gaap',
                       'tags': ['AircraftMaintenanceMaterialsAndRepairs'],
                       'unit': 'USD',
                       'domain': 'Operating Costs'},
 'flight_equipment_capex': {'label': 'Payments for Flight Equipment',
                            'namespace': 'us-gaap',
                            'tags': ['PaymentsForFlightEquipment'],
                            'unit': 'USD',
                            'domain': 'Capital Expenditure'},
 'ppe_net': {'label': 'Property, Plant & Equipment, Net',
             'namespace': 'us-gaap',
             'tags': ['PropertyPlantAndEquipmentNet',
                      'PropertyPlantAndEquipmentAndFinanceLeaseRightOfUseAssetAfterAccumulatedDepreciationAndAmortization'],
             'unit': 'USD',
             'domain': 'Balance Sheet'},
 'air_traffic_liability': {'label': 'Air Traffic Liability',
                           'namespace': 'us-gaap',
                           'tags': ['AirTrafficLiabilityCurrent'],
                           'unit': 'USD',
                           'domain': 'Working Capital'},
 'employees': {'label': 'Employees',
               'namespace': 'dei',
               'tags': ['EntityNumberOfEmployees'],
               'unit': 'employee',
               'domain': 'Workforce'}}

NETWORK_KPIS = [('passengers', 'Passengers', 'count', 'Reported', 'SUM(passengers)'),
 ('seats', 'Available Seats', 'count', 'Reported', 'SUM(seats)'),
 ('asm', 'Available Seat Miles (ASM)', 'seat-miles', 'Derived', 'SUM(seats * distance_miles)'),
 ('rpm', 'Revenue Passenger Miles (RPM)', 'passenger-miles', 'Derived', 'SUM(passengers * distance_miles)'),
 ('load_factor', 'Load Factor', '%', 'Derived', 'RPM / ASM'),
 ('departures_performed', 'Departures Performed', 'count', 'Reported', 'SUM(departures_performed)'),
 ('departures_scheduled', 'Departures Scheduled', 'count', 'Reported', 'SUM(departures_scheduled)'),
 ('completion_rate', 'Completion Rate', '%', 'Derived', 'Departures Performed / Departures Scheduled'),
 ('passengers_per_departure',
  'Passengers per Departure',
  'passengers/departure',
  'Derived',
  'Passengers / Departures Performed'),
 ('average_stage_length',
  'Average Stage Length',
  'miles',
  'Derived',
  'SUM(distance * departures performed) / SUM(departures performed)'),
 ('freight_pounds', 'Freight Transported', 'lb', 'Reported', 'SUM(freight_pounds)'),
 ('mail_pounds', 'Mail Transported', 'lb', 'Reported', 'SUM(mail_pounds)'),
 ('airborne_hours', 'Airborne Time', 'hours', 'Derived', 'SUM(airborne_minutes) / 60')]

FPNA_KPIS = [('revenue_growth_yoy',
  'Revenue Growth YoY',
  '%',
  'Derived',
  '(Revenue_t / Revenue_t-1) - 1',
  'Financial Performance'),
 ('operating_margin', 'Operating Margin', '%', 'Derived', 'Operating Income / Revenue', 'Profitability'),
 ('free_cash_flow',
  'Free Cash Flow',
  'USD',
  'Derived',
  'Operating Cash Flow - capital expenditures available in model',
  'Cash Flow'),
 ('actual_vs_budget', 'Actual vs Budget Variance', 'USD', 'Modeled', 'Actual - Budget', 'FP&A'),
 ('actual_vs_budget_pct',
  'Actual vs Budget Variance %',
  '%',
  'Modeled',
  '(Actual - Budget) / Budget',
  'FP&A'),
 ('actual_vs_forecast', 'Actual vs Forecast Variance', 'USD', 'Modeled', 'Actual - Forecast', 'FP&A'),
 ('forecast_accuracy',
  'Forecast Accuracy',
  '%',
  'Modeled',
  '1 - ABS(Actual - Forecast) / ABS(Actual)',
  'FP&A'),
 ('forecast_bias', 'Forecast Bias', '%', 'Modeled', '(Forecast - Actual) / ABS(Actual)', 'FP&A'),
 ('fuel_cost_per_asm',
  'Fuel Cost per ASM',
  'USD/ASM',
  'Derived',
  'Fuel Costs / ASM (aligned period)',
  'Unit Economics'),
 ('revenue_per_asm',
  'Revenue per ASM',
  'USD/ASM',
  'Derived',
  'Revenue / ASM (aligned period)',
  'Unit Economics')]
